
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightASIGNARleftSUMARESTAleftMULTDIVleftMAYORMENORMAYOR_IGUALMENOR_IGUALleftANDORAND ASIGNAR COMA CORCHETE_DER CORCHETE_IZQ DECIMALSTRING DIFERENTE DIV DOSPUNTOS ID IGUAL INTERROGACION LLAVE_DER LLAVE_IZQ MAYOR MAYOR_IGUAL MENOR MENOR_IGUAL MODULO MULT NOT NUMERO OR PALABRA_RESERVADA PARENT_DER PARENT_IZQ PUNTO PUNTOCOMA RESTA SUMAexpression : expression SUMA expression\n                   | expression RESTA expression\n                   | expression MULT expression\n                   | expression DIV expressionexpression : NUMEROexpression : PARENT_IZQ expression PARENT_DERexpression : ID ASIGNAR expressionexpression : expression AND expressionexpression : expression OR expression'
    
_lr_action_items = {'NUMERO':([0,3,5,6,7,8,9,10,12,],[2,2,2,2,2,2,2,2,2,]),'PARENT_IZQ':([0,3,5,6,7,8,9,10,12,],[3,3,3,3,3,3,3,3,3,]),'ID':([0,3,5,6,7,8,9,10,12,],[4,4,4,4,4,4,4,4,4,]),'$end':([1,2,13,14,15,16,17,18,19,20,],[0,-5,-1,-2,-3,-4,-8,-9,-6,-7,]),'SUMA':([1,2,11,13,14,15,16,17,18,19,20,],[5,-5,5,-1,-2,-3,-4,-8,-9,-6,5,]),'RESTA':([1,2,11,13,14,15,16,17,18,19,20,],[6,-5,6,-1,-2,-3,-4,-8,-9,-6,6,]),'MULT':([1,2,11,13,14,15,16,17,18,19,20,],[7,-5,7,7,7,-3,-4,-8,-9,-6,7,]),'DIV':([1,2,11,13,14,15,16,17,18,19,20,],[8,-5,8,8,8,-3,-4,-8,-9,-6,8,]),'AND':([1,2,11,13,14,15,16,17,18,19,20,],[9,-5,9,9,9,9,9,-8,-9,-6,9,]),'OR':([1,2,11,13,14,15,16,17,18,19,20,],[10,-5,10,10,10,10,10,-8,-9,-6,10,]),'PARENT_DER':([2,11,13,14,15,16,17,18,19,20,],[-5,19,-1,-2,-3,-4,-8,-9,-6,-7,]),'ASIGNAR':([4,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,5,6,7,8,9,10,12,],[1,11,13,14,15,16,17,18,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression SUMA expression','expression',3,'p_expression_binop','sintactico.py',13),
  ('expression -> expression RESTA expression','expression',3,'p_expression_binop','sintactico.py',14),
  ('expression -> expression MULT expression','expression',3,'p_expression_binop','sintactico.py',15),
  ('expression -> expression DIV expression','expression',3,'p_expression_binop','sintactico.py',16),
  ('expression -> NUMERO','expression',1,'p_expression_number','sintactico.py',28),
  ('expression -> PARENT_IZQ expression PARENT_DER','expression',3,'p_expression_parentheses','sintactico.py',32),
  ('expression -> ID ASIGNAR expression','expression',3,'p_expression_assign','sintactico.py',39),
  ('expression -> expression AND expression','expression',3,'p_expression_and','sintactico.py',43),
  ('expression -> expression OR expression','expression',3,'p_expression_or','sintactico.py',47),
]
